[2025-09-16T15:58:39.766+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_pipeline_postgres.extract manual__2025-09-16T15:58:37.300833+00:00 [queued]>
[2025-09-16T15:58:39.770+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_pipeline_postgres.extract manual__2025-09-16T15:58:37.300833+00:00 [queued]>
[2025-09-16T15:58:39.770+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-09-16T15:58:39.778+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract> on 2025-09-16 15:58:37.300833+00:00
[2025-09-16T15:58:39.782+0000] {standard_task_runner.py:57} INFO - Started process 247 to run task
[2025-09-16T15:58:39.784+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_pipeline_postgres', 'extract', 'manual__2025-09-16T15:58:37.300833+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados.py', '--cfg-path', '/tmp/tmp41z1ky61']
[2025-09-16T15:58:39.786+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask extract
[2025-09-16T15:58:39.815+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_pipeline_postgres.extract manual__2025-09-16T15:58:37.300833+00:00 [running]> on host f0ba1f59a373
[2025-09-16T15:58:39.861+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_pipeline_postgres' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T15:58:37.300833+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-16T15:58:37.300833+00:00'
[2025-09-16T15:58:40.204+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-09-16T15:58:40.212+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=crypto_pipeline_postgres, task_id=extract, execution_date=20250916T155837, start_date=20250916T155839, end_date=20250916T155840
[2025-09-16T15:58:40.237+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-16T15:58:40.254+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
