[2025-09-16T16:09:34.396+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_pipeline_postgres.extract manual__2025-09-16T16:09:32.190871+00:00 [queued]>
[2025-09-16T16:09:34.401+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_pipeline_postgres.extract manual__2025-09-16T16:09:32.190871+00:00 [queued]>
[2025-09-16T16:09:34.401+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-09-16T16:09:34.409+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract> on 2025-09-16 16:09:32.190871+00:00
[2025-09-16T16:09:34.413+0000] {standard_task_runner.py:57} INFO - Started process 241 to run task
[2025-09-16T16:09:34.415+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_pipeline_postgres', 'extract', 'manual__2025-09-16T16:09:32.190871+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados.py', '--cfg-path', '/tmp/tmpp1q1glyb']
[2025-09-16T16:09:34.417+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask extract
[2025-09-16T16:09:34.445+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_pipeline_postgres.extract manual__2025-09-16T16:09:32.190871+00:00 [running]> on host 529eb878ec8c
[2025-09-16T16:09:34.489+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_pipeline_postgres' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T16:09:32.190871+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-16T16:09:32.190871+00:00'
[2025-09-16T16:09:35.101+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-09-16T16:09:35.108+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=crypto_pipeline_postgres, task_id=extract, execution_date=20250916T160932, start_date=20250916T160934, end_date=20250916T160935
[2025-09-16T16:09:35.148+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-16T16:09:35.165+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
